### ISSUE TITLE
Blockade up execution error 

### ISSUE THREAD

**Issue by ljwango** [dcm-oss/blockade#23]
When I perform blockade up and submit them to the mistake, where is the problem? How to solve?

**Comment by ljwango** [comment]
Unexpected error! This may be a Blockade bug.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockade-0.2.0-py2.7.egg/blockade/cli.py", line 326, in main
    opts.func(opts)
  File "/usr/local/lib/python2.7/dist-packages/blockade-0.2.0-py2.7.egg/blockade/cli.py", line 122, in cmd_up
    force=opts.force)
  File "/usr/local/lib/python2.7/dist-packages/blockade-0.2.0-py2.7.egg/blockade/core.py", line 81, in create
    container_id = self._start_container(blockade_id, container, force)
  File "/usr/local/lib/python2.7/dist-packages/blockade-0.2.0-py2.7.egg/blockade/core.py", line 145, in _start_container
    container_id = create_container()
  File "/usr/local/lib/python2.7/dist-packages/blockade-0.2.0-py2.7.egg/blockade/core.py", line 140, in create_container
    labels={"blockade.id": blockade_id})
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/api/container.py", line 117, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/api/container.py", line 128, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/client.py", line 146, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker_py-1.6.0-py2.7.egg/docker/client.py", line 141, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
NotFound: 404 Client Error: Not Found ("client and server don't have same version (client : 1.21, server: 1.12)")

**Comment by labisso** [comment]
Hello, please try with Docker version 1.9 or later.

I'm leaving this issue open because 1) Blockade probably doesn't need to actually require 1.9 and 2) we should handle this failure more gracefully.

**Comment by labisso** [comment]
Closing this issue. In 0.3.1, blockade has a couple of fixes that address problems discussed here:
1. Vastly improved error handling around finding a container's interface
2. `ip` is no longer required to be installed in containers. Instead Blockade directly reads the `/sys` FS to find the needed information from the container.
